### ISSUE TITLE
UI login page

### ISSUE THREAD

**Issue by erickDevUp** [joaquindev23/FrontEnd_LLM#1]
![Login](https://github.com/joaquindev23/FrontEnd_LLM/assets/104710949/e5472d82-1059-43c1-982b-c8b577abfd08)

**Comment by joaquindev23** [comment]
Exclente, de a poco se va construyendo! Sientete libre de agregarle lo que haga falta, algun enlace, referencia, ayuda, etc ... Es la base, de ahi en mas estoy seguro que tendras una excelente imaginacion

**Comment by erickDevUp** [comment]
not created yet

**Comment by joaquindev23** [comment]
Entendido
