### ISSUE TITLE
UI Register Page

### ISSUE THREAD

**Issue by erickDevUp** [joaquindev23/FrontEnd_LLM#2]
![Register](https://github.com/joaquindev23/FrontEnd_LLM/assets/104710949/2e729396-8de6-43c9-8efa-d5f27e737a72)

**Comment by joaquindev23** [comment]
Sientete libre de agregarle lo que haga falta, algun enlace, referencia, ayuda, etc ...

**Comment by erickDevUp** [comment]
no created yet

**Comment by joaquindev23** [comment]
Entendido
