### ISSUE TITLE
Persistencia temporal de chat (frontend)

### ISSUE THREAD

**Issue by RosanneVN** [joaquindev23/FrontEnd_LLM#21]
Recomendado utilizar indexDB

**Comment by RosanneVN** [comment]
![image](https://github.com/joaquindev23/FrontEnd_LLM/assets/136199555/e8421a73-c6e6-448b-a64b-e01f4e43c13f)
![image](https://github.com/joaquindev23/FrontEnd_LLM/assets/136199555/44c2c896-0776-4075-9f6a-bef1bc47b0b8)

**Comment by erickDevUp** [comment]
Gran trabajo
