### ISSUE TITLE
UI Verification Page

### ISSUE THREAD

**Issue by erickDevUp** [joaquindev23/FrontEnd_LLM#3]
![Verificacion](https://github.com/joaquindev23/FrontEnd_LLM/assets/104710949/041ec215-4d68-4b09-828d-f8632c090b5b)

**Comment by joaquindev23** [comment]
Sientete llibre tambien de poder agregarle las transiciones y efectos que quieras

**Comment by erickDevUp** [comment]
no created yet

**Comment by erickDevUp** [comment]
no created yet

**Comment by joaquindev23** [comment]
Entendido
