### ISSUE TITLE
UI Error Page 

### ISSUE THREAD

**Issue by erickDevUp** [joaquindev23/FrontEnd_LLM#4]
![Error 405](https://github.com/joaquindev23/FrontEnd_LLM/assets/104710949/1ce09e36-bf50-4b87-af3e-90059a7ce5e2)

**Comment by joaquindev23** [comment]
Good!

**Comment by erickDevUp** [comment]
no created yet

**Comment by joaquindev23** [comment]
Entendido, no hay problema

**Comment by jsha64** [comment]
Este apartado esta listo solo le faltan detalles

**Comment by joaquindev23** [comment]
Que es lo que sucede

**Comment by erickDevUp** [comment]
done
