### ISSUE TITLE
UI Chat Page

### ISSUE THREAD

**Issue by erickDevUp** [joaquindev23/FrontEnd_LLM#5]
![Home recomendaciones](https://github.com/joaquindev23/FrontEnd_LLM/assets/104710949/a69e62a7-ef50-4298-9b6e-d548a72953ed)
![Conversaciones](https://github.com/joaquindev23/FrontEnd_LLM/assets/104710949/12d095c6-c749-48f6-91d4-47d2d1113d28)

**Comment by joaquindev23** [comment]
Arte pura! Gran trabajo!

**Comment by joaquindev23** [comment]
Si hace falta algo agregalo sin problema
