### ISSUE TITLE
UI IA Page

### ISSUE THREAD

**Issue by erickDevUp** [joaquindev23/FrontEnd_LLM#6]
![Inicio vacio IA Creadas carga](https://github.com/joaquindev23/FrontEnd_LLM/assets/104710949/b6540077-6e91-40b9-a380-c67d1eef5d65)
![Inicio vacio IA Creadas carga (1)](https://github.com/joaquindev23/FrontEnd_LLM/assets/104710949/5a638a48-31e3-410e-b05b-30da4a41900c)

**Comment by joaquindev23** [comment]
Tiene una estetica impresionandote, felicidades! Sientente libre de agregarle lo que sea necesario

**Comment by joaquindev23** [comment]
Si sientes que falta algo, agregalo sin problema
